[package]
name = "buddy"
version = "0.1.0"
authors = ["Sean McConnell <sean66chon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
base64 = "0.13.0"
checksums = "0.9.0"
snappy = "0.4.0"